### ISSUE TITLE
List index out of range when printing lots

### ISSUE THREAD

**Issue by tompreston** [piface/pifacecad#2]
```
import pifacecad


if __name__ == '__main__':
    cad = pifacecad.PiFaceCAD()
    cad.lcd.backlight_on()

    while True:
        cad.lcd.write("Hello EMC!")
```

Causes:

```
Traceback (most recent call last):
  File "pfcad_emc.py", line 9, in <module>
    cad.lcd.write("Hello EMC!")
  File "/usr/lib/python3/dist-packages/pifacecad/lcd.py", line 438, in write
    self.set_ddram_address()
  File "/usr/lib/python3/dist-packages/pifacecad/lcd.py", line 350, in set_ddram_address
    address = self.colrow2address(col, row)
  File "/usr/lib/python3/dist-packages/pifacecad/lcd.py", line 393, in colrow2address
    return col + ROW_OFFSETS[int(row)]
IndexError: list index out of range
```

After a short while.

**Comment by potzenhotz** [comment]
Following solution should work:

- event.chip.lcd.set_cursor(0,0) --> starts writing at the beginning

- event.chip.lcd.clear() --> clears the lcd
