### ISSUE TITLE
sysinfo.py error : could not convert string to float:

### ISSUE THREAD

**Issue by JBSchueler** [piface/pifacecad#32]
- RPi1
- Raspbian Buster Lite
- PiFace Control and Display 2

while trying to execute the sysinfo.py example I get this error...

```linux
pi@raspberrypi:~ $ python ./pifacecad/examples/sysinfo.py
Traceback (most recent call last):
  File "./pifacecad/examples/sysinfo.py", line 75, in <module>
    show_sysinfo()
  File "./pifacecad/examples/sysinfo.py", line 56, in show_sysinfo
    cad.lcd.write(":{}".format(get_my_free_mem()))
  File "./pifacecad/examples/sysinfo.py", line 35, in get_my_free_mem
    used_mem = float(run_cmd(USED_MEM_CMD))
ValueError: could not convert string to float:
pi@raspberrypi:~ $
```
```
pi@raspberrypi:~ $ python3 ./pifacecad/examples/sysinfo.py
Traceback (most recent call last):
  File "./pifacecad/examples/sysinfo.py", line 75, in <module>
    show_sysinfo()
  File "./pifacecad/examples/sysinfo.py", line 56, in show_sysinfo
    cad.lcd.write(":{}".format(get_my_free_mem()))
  File "./pifacecad/examples/sysinfo.py", line 35, in get_my_free_mem
    used_mem = float(run_cmd(USED_MEM_CMD))
ValueError: could not convert string to float:
pi@raspberrypi:~ $
```

**Comment by JBSchueler** [comment]
Probably related to #26 which seems to be closed...
